# Generated by Django 2.2.5 on 2019-11-04 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='followtalk',
            name='talk',
        ),
        migrations.AddField(
            model_name='followtalk',
            name='talk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='talks.Talk'),
        ),
        migrations.AlterField(
            model_name='followtalk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows_talk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.AddField(
            model_name='likepost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='talks.Post'),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userfollowuser',
            name='being_followed',
        ),
        migrations.AddField(
            model_name='userfollowuser',
            name='being_followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollowuser',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
